language: ruby
rvm:
  - 2.3.1
services: 
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - bundle install
cache: bundler
git:
  depth: 3